const BookingsData = [
  {
    id: "bkg1",
    name: "John Smith",
    email: "john.smith@example.com",
    packageId: "pkg15",
    phoneNumber: "+94771234567",
    tickets: 2,
    date: "2025-02-10",
    specialNotes: "Need vegetarian meals.",
  },
  {
    id: "bkg2",
    name: "Emily Johnson",
    email: "emily.johnson@example.com",
    packageId: "pkg42",
    phoneNumber: "+94776543210",
    tickets: 4,
    date: "2025-02-12",
    specialNotes: "Request aisle seats.",
  },
  {
    id: "bkg3",
    name: "Michael Davis",
    email: "michael.davis@example.com",
    packageId: "pkg7",
    phoneNumber: "+94778901234",
    tickets: 3,
    date: "2025-02-15",
    specialNotes: "No special requirements.",
  },
  {
    id: "bkg4",
    name: "Sarah Miller",
    email: "sarah.miller@example.com",
    packageId: "pkg23",
    phoneNumber: "+94770123456",
    tickets: 1,
    date: "2025-02-18",
    specialNotes: "Require a wheelchair.",
  },
  {
    id: "bkg5",
    name: "Daniel Wilson",
    email: "daniel.wilson@example.com",
    packageId: "pkg30",
    phoneNumber: "+94776789123",
    tickets: 2,
    date: "2025-02-20",
    specialNotes: "Need early check-in.",
  },
  {
    id: "bkg6",
    name: "Sophia Brown",
    email: "sophia.brown@example.com",
    packageId: "pkg9",
    phoneNumber: "+94778965432",
    tickets: 5,
    date: "2025-02-22",
    specialNotes: "Celebrating a birthday.",
  },
  {
    id: "bkg7",
    name: "James Anderson",
    email: "james.anderson@example.com",
    packageId: "pkg48",
    phoneNumber: "+94779812345",
    tickets: 3,
    date: "2025-02-25",
    specialNotes: "Require halal meals.",
  },
  {
    id: "bkg8",
    name: "Olivia Martinez",
    email: "olivia.martinez@example.com",
    packageId: "pkg2",
    phoneNumber: "+94777098765",
    tickets: 6,
    date: "2025-02-28",
    specialNotes: "Request VIP seats.",
  },
  {
    id: "bkg9",
    name: "Ethan Moore",
    email: "ethan.moore@example.com",
    packageId: "pkg36",
    phoneNumber: "+94778987654",
    tickets: 4,
    date: "2025-03-01",
    specialNotes: "No peanuts in meals.",
  },
  {
    id: "bkg10",
    name: "Ava Taylor",
    email: "ava.taylor@example.com",
    packageId: "pkg51",
    phoneNumber: "+94776655443",
    tickets: 2,
    date: "2025-03-05",
    specialNotes: "Traveling with an infant.",
  },
  {
    id: "bkg11",
    name: "Liam Harris",
    email: "liam.harris@example.com",
    packageId: "pkg18",
    phoneNumber: "+94771236789",
    tickets: 3,
    date: "2025-03-10",
    specialNotes: "Allergic to gluten.",
  },
  {
    id: "bkg12",
    name: "Isabella Martin",
    email: "isabella.martin@example.com",
    packageId: "pkg33",
    phoneNumber: "+94777654321",
    tickets: 1,
    date: "2025-03-12",
    specialNotes: "Need assistance boarding.",
  },
  {
    id: "bkg13",
    name: "Noah Garcia",
    email: "noah.garcia@example.com",
    packageId: "pkg45",
    phoneNumber: "+94777890123",
    tickets: 2,
    date: "2025-03-15",
    specialNotes: "Prefer window seats.",
  },
  {
    id: "bkg14",
    name: "Mia Clark",
    email: "mia.clark@example.com",
    packageId: "pkg12",
    phoneNumber: "+94770112233",
    tickets: 4,
    date: "2025-03-18",
    specialNotes: "Traveling for an anniversary.",
  },
  {
    id: "bkg15",
    name: "Elijah Lewis",
    email: "elijah.lewis@example.com",
    packageId: "pkg6",
    phoneNumber: "+94779876543",
    tickets: 5,
    date: "2025-03-20",
    specialNotes: "Group of teenagers.",
  },
  {
    id: "bkg16",
    name: "Charlotte Walker",
    email: "charlotte.walker@example.com",
    packageId: "pkg27",
    phoneNumber: "+94777567890",
    tickets: 3,
    date: "2025-03-22",
    specialNotes: "Special meal for a diabetic.",
  },
  {
    id: "bkg17",
    name: "Benjamin Hall",
    email: "benjamin.hall@example.com",
    packageId: "pkg50",
    phoneNumber: "+94778943210",
    tickets: 6,
    date: "2025-03-25",
    specialNotes: "Celebrating a graduation.",
  },
  {
    id: "bkg18",
    name: "Emma Allen",
    email: "emma.allen@example.com",
    packageId: "pkg3",
    phoneNumber: "+94777765432",
    tickets: 2,
    date: "2025-03-28",
    specialNotes: "Vegetarian meals required.",
  },
  {
    id: "bkg19",
    name: "Oliver Young",
    email: "oliver.young@example.com",
    packageId: "pkg39",
    phoneNumber: "+94777678901",
    tickets: 4,
    date: "2025-04-01",
    specialNotes: "Flexible with seating.",
  },
  {
    id: "bkg20",
    name: "Sophia Hernandez",
    email: "sophia.hernandez@example.com",
    packageId: "pkg21",
    phoneNumber: "+94778876543",
    tickets: 1,
    date: "2025-04-05",
    specialNotes: "Need assistance with luggage.",
  },
];

export default BookingsData;
