const TravelPackages = [
  {
    name: "Majestic Paris Explorer",
    duration: 5,
    country: "France",
    highlights: ["Eiffel Tower", "Louvre Museum", "Seine Cruise"],
    price: 1899,
    rating: 5,
    image: "https://picsum.photos/400/250?random=1",
    batch: null,
    id: "pkg1",
  },
  {
    name: "French Riviera Dream",
    duration: 7,
    country: "France",
    highlights: ["Nice Beaches", "Monaco Visit", "Wine Tasting"],
    price: 2499,
    rating: 4,
    image: "https://picsum.photos/400/250?random=2",
    batch: "popular",
    id: "pkg2",
  },
  {
    name: "Loire Valley Escape",
    duration: 4,
    country: "France",
    highlights: ["Castle Tours", "Garden Visits", "Local Cuisine"],
    price: 1599,
    rating: 4,
    image: "https://picsum.photos/400/250?random=3",
    batch: null,
    id: "pkg3",
  },
  {
    name: "Provence Adventure",
    duration: 6,
    country: "France",
    highlights: ["Lavender Fields", "Historic Villages", "Art Tours"],
    price: 2199,
    rating: 5,
    image: "https://picsum.photos/400/250?random=4",
    batch: null,
    id: "pkg4",
  },
  {
    name: "Normandy Discovery",
    duration: 5,
    country: "France",
    highlights: ["D-Day Beaches", "Mont Saint-Michel", "Local History"],
    price: 1799,
    rating: 4,
    image: "https://picsum.photos/400/250?random=5",
    batch: null,
    id: "pkg5",
  },
  {
    name: "Burgundy Wine Trail",
    duration: 4,
    country: "France",
    highlights: ["Wine Tours", "Dijon Exploring", "Gastronomy Experience"],
    price: 1699,
    rating: 4,
    image: "https://picsum.photos/400/250?random=6",
    batch: "popular",
    id: "pkg6",
  },
  {
    name: "Tokyo Essentials",
    duration: 6,
    country: "Japan",
    highlights: ["Shibuya Crossing", "Temple Tours", "Sushi Experience"],
    price: 2499,
    rating: 5,
    image: "https://picsum.photos/400/250?random=7",
    batch: null,
    id: "pkg7",
  },
  {
    name: "Kyoto Cultural Journey",
    duration: 5,
    country: "Japan",
    highlights: ["Temple Circuit", "Tea Ceremony", "Bamboo Forest"],
    price: 2199,
    rating: 5,
    image: "https://picsum.photos/400/250?random=8",
    batch: null,
    id: "pkg8",
  },
  {
    name: "Mount Fuji Adventure",
    duration: 4,
    country: "Japan",
    highlights: ["Fuji Climb", "Hot Springs", "Lake Views"],
    price: 1799,
    rating: 4,
    image: "https://picsum.photos/400/250?random=9",
    batch: "popular",
    id: "pkg9",
  },
  {
    name: "Osaka Foodie Tour",
    duration: 5,
    country: "Japan",
    highlights: ["Street Food", "Castle Visit", "Night Markets"],
    price: 1999,
    rating: 4,
    image: "https://picsum.photos/400/250?random=10",
    batch: null,
    id: "pkg10",
  },
  {
    name: "Hokkaido Winter Magic",
    duration: 7,
    country: "Japan",
    highlights: ["Snow Festival", "Ski Resort", "Winter Sports"],
    price: 2899,
    rating: 5,
    image: "https://picsum.photos/400/250?random=11",
    batch: "new",
    id: "pkg11",
  },
  {
    name: "Okinawa Island Hopping",
    duration: 6,
    country: "Japan",
    highlights: ["Beach Paradise", "Marine Adventure", "Island Culture"],
    price: 2399,
    rating: 4,
    image: "https://picsum.photos/400/250?random=12",
    batch: null,
    id: "pkg12",
  },
  {
    name: "Rome Imperial Tour",
    duration: 5,
    country: "Italy",
    highlights: ["Colosseum Visit", "Vatican Tour", "Roman Forum"],
    price: 1999,
    rating: 5,
    image: "https://picsum.photos/400/250?random=13",
    batch: "new",
    id: "pkg13",
  },
  {
    name: "Tuscan Countryside",
    duration: 7,
    country: "Italy",
    highlights: ["Wine Tasting", "Cooking Class", "Village Tours"],
    price: 2599,
    rating: 5,
    image: "https://picsum.photos/400/250?random=14",
    batch: null,
    id: "pkg14",
  },
  {
    name: "Venice Romance",
    duration: 4,
    country: "Italy",
    highlights: ["Gondola Ride", "Murano Glass", "St Mark's"],
    price: 1799,
    rating: 4,
    image: "https://picsum.photos/400/250?random=15",
    batch: "new",
    id: "pkg15",
  },
  {
    name: "Amalfi Coast Dream",
    duration: 6,
    country: "Italy",
    highlights: ["Coastal Drive", "Limoncello Tasting", "Beach Time"],
    price: 2399,
    rating: 5,
    image: "https://picsum.photos/400/250?random=16",
    batch: null,
    id: "pkg16",
  },
  {
    name: "Sicily Adventure",
    duration: 8,
    country: "Italy",
    highlights: ["Mount Etna", "Greek Ruins", "Local Cuisine"],
    price: 2799,
    rating: 4,
    image: "https://picsum.photos/400/250?random=17",
    batch: null,
    id: "pkg17",
  },
  {
    name: "Milan Fashion Week",
    duration: 5,
    country: "Italy",
    highlights: ["Fashion Shows", "Shopping Tours", "Design Districts"],
    price: 2199,
    rating: 4,
    image: "https://picsum.photos/400/250?random=18",
    batch: null,
    id: "pkg18",
  },
  {
    name: "Barcelona Highlights",
    duration: 5,
    country: "Spain",
    highlights: ["Sagrada Familia", "Gothic Quarter", "Tapas Tour"],
    price: 1899,
    rating: 5,
    image: "https://picsum.photos/400/250?random=19",
    batch: null,
    id: "pkg19",
  },
  {
    name: "Madrid Royal Tour",
    duration: 4,
    country: "Spain",
    highlights: ["Royal Palace", "Prado Museum", "Plaza Mayor"],
    price: 1699,
    rating: 4,
    image: "https://picsum.photos/400/250?random=20",
    batch: null,
    id: "pkg20",
  },
  {
    name: "Andalusian Journey",
    duration: 7,
    country: "Spain",
    highlights: ["Alhambra Palace", "Flamenco Show", "Moorish Architecture"],
    price: 2499,
    rating: 5,
    image: "https://picsum.photos/400/250?random=21",
    batch: null,
    id: "pkg21",
  },
  {
    name: "Ibiza Party Week",
    duration: 6,
    country: "Spain",
    highlights: ["Beach Clubs", "Sunset Strip", "Party Boats"],
    price: 2299,
    rating: 4,
    image: "https://picsum.photos/400/250?random=22",
    batch: null,
    id: "pkg22",
  },
  {
    name: "Valencia Culture",
    duration: 5,
    country: "Spain",
    highlights: ["City Arts", "Paella Experience", "Beach Time"],
    price: 1899,
    rating: 4,
    image: "https://picsum.photos/400/250?random=23",
    batch: null,
    id: "pkg23",
  },
  {
    name: "Basque Country Explorer",
    duration: 6,
    country: "Spain",
    highlights: ["Pintxos Tour", "Guggenheim Museum", "Coastal Villages"],
    price: 2199,
    rating: 5,
    image: "https://picsum.photos/400/250?random=24",
    batch: null,
    id: "pkg24",
  },
  {
    name: "Athens Ancient Tour",
    duration: 4,
    country: "Greece",
    highlights: ["Acropolis Visit", "Plaka District", "Ancient Agora"],
    price: 1699,
    rating: 5,
    image: "https://picsum.photos/400/250?random=25",
    batch: null,
    id: "pkg25",
  },
  {
    name: "Santorini Dreams",
    duration: 6,
    country: "Greece",
    highlights: ["Sunset Views", "Wine Tasting", "Beach Time"],
    price: 2499,
    rating: 5,
    image: "https://picsum.photos/400/250?random=26",
    batch: null,
    id: "pkg26",
  },
  {
    name: "Mykonos Party",
    duration: 5,
    country: "Greece",
    highlights: ["Beach Clubs", "Island Hopping", "Windmill Views"],
    price: 2199,
    rating: 4,
    image: "https://picsum.photos/400/250?random=27",
    batch: null,
    id: "pkg27",
  },
  {
    name: "Crete Discovery",
    duration: 7,
    country: "Greece",
    highlights: ["Minoan Palace", "Beach Adventure", "Mountain Villages"],
    price: 2399,
    rating: 4,
    image: "https://picsum.photos/400/250?random=28",
    batch: null,
    id: "pkg28",
  },
  {
    name: "Rhodes Knight Tour",
    duration: 5,
    country: "Greece",
    highlights: ["Medieval City", "Ancient Sites", "Beach Relaxation"],
    price: 1899,
    rating: 4,
    image: "https://picsum.photos/400/250?random=29",
    batch: null,
    id: "pkg29",
  },
  {
    name: "Corfu Island Life",
    duration: 6,
    country: "Greece",
    highlights: ["Venetian Fortress", "Olive Groves", "Crystal Beaches"],
    price: 2099,
    rating: 4,
    image: "https://picsum.photos/400/250?random=30",
    batch: null,
    id: "pkg30",
  },
  {
    name: "Swiss Alps Adventure",
    duration: 7,
    country: "Switzerland",
    highlights: ["Skiing Paradise", "Mountain Views", "Cable Cars"],
    price: 2899,
    rating: 5,
    image: "https://picsum.photos/400/250?random=31",
    batch: null,
    id: "pkg31",
  },
  {
    name: "Geneva Lake Tour",
    duration: 4,
    country: "Switzerland",
    highlights: ["Lake Cruise", "Watch Museums", "Old Town"],
    price: 1999,
    rating: 4,
    image: "https://picsum.photos/400/250?random=32",
    batch: null,
    id: "pkg32",
  },
  {
    name: "Zurich City Break",
    duration: 5,
    country: "Switzerland",
    highlights: ["Shopping District", "Lake Activities", "Cultural Tour"],
    price: 2199,
    rating: 4,
    image: "https://picsum.photos/400/250?random=33",
    batch: null,
    id: "pkg33",
  },
  {
    name: "Lucerne Experience",
    duration: 6,
    country: "Switzerland",
    highlights: ["Chapel Bridge", "Mount Pilatus", "Lake Views"],
    price: 2399,
    rating: 5,
    image: "https://picsum.photos/400/250?random=34",
    batch: null,
    id: "pkg34",
  },
  {
    name: "Interlaken Adventure",
    duration: 8,
    country: "Switzerland",
    highlights: ["Jungfrau Railway", "Adventure Sports", "Alpine Lakes"],
    price: 2999,
    rating: 5,
    image: "https://picsum.photos/400/250?random=35",
    batch: null,
    id: "pkg35",
  },
  {
    name: "Zermatt Escape",
    duration: 5,
    country: "Switzerland",
    highlights: ["Matterhorn View", "Mountain Hiking", "Glacier Paradise"],
    price: 2499,
    rating: 5,
    image: "https://picsum.photos/400/250?random=36",
    batch: null,
    id: "pkg36",
  },
  {
    name: "Bali Beach Paradise",
    duration: 8,
    country: "Indonesia",
    highlights: ["Sunset Beaches", "Temple Tours", "Spa Treatments"],
    price: 1999,
    rating: 5,
    image: "https://picsum.photos/400/250?random=37",
    batch: null,
    id: "pkg37",
  },
  {
    name: "Safari Adventure",
    duration: 7,
    country: "Indonesia",
    highlights: ["Wildlife Viewing", "Masai Village", "Sunset Safari"],
    price: 3299,
    rating: 5,
    image: "https://picsum.photos/400/250?random=38",
    batch: null,
    id: "pkg38",
  },
  {
    name: "Raja Ampat Diving",
    duration: 8,
    country: "Indonesia",
    highlights: ["Coral Reefs", "Island Hopping", "Marine Life"],
    price: 2999,
    rating: 5,
    image: "https://picsum.photos/400/250?random=39",
    batch: null,
    id: "pkg39",
  },
  {
    name: "Komodo Explorer",
    duration: 6,
    country: "Indonesia",
    highlights: ["Dragon Watching", "Snorkeling Adventure", "Pink Beach"],
    price: 2299,
    rating: 5,
    image: "https://picsum.photos/400/250?random=40",
    batch: null,
    id: "pkg40",
  },
  {
    name: "Sumatra Adventure",
    duration: 7,
    country: "Indonesia",
    highlights: ["Lake Toba", "Tribal Villages", "Coffee Plantations"],
    price: 2199,
    rating: 4,
    image: "https://picsum.photos/400/250?random=41",
    batch: null,
    id: "pkg41",
  },
  {
    name: "Yogyakarta Heritage",
    duration: 5,
    country: "Indonesia",
    highlights: ["Borobudur Temple", "Batik Making", "Royal Palace"],
    price: 1799,
    rating: 4,
    image: "https://picsum.photos/400/250?random=42",
    batch: null,
    id: "pkg42",
  },
  {
    name: "Bangkok Explorer",
    duration: 5,
    country: "Thailand",
    highlights: ["Temple Tour", "River Cruise", "Street Food"],
    price: 1699,
    rating: 4,
    image: "https://picsum.photos/400/250?random=43",
    batch: null,
    id: "pkg43",
  },
  {
    name: "Phuket Paradise",
    duration: 7,
    country: "Thailand",
    highlights: ["Island Hopping", "Beach Relaxation", "Night Markets"],
    price: 2199,
    rating: 5,
    image: "https://picsum.photos/400/250?random=44",
    batch: null,
    id: "pkg44",
  },
  {
    name: "Chiang Mai Culture",
    duration: 6,
    country: "Thailand",
    highlights: ["Temple Visit", "Elephant Sanctuary", "Cooking Class"],
    price: 1899,
    rating: 4,
    image: "https://picsum.photos/400/250?random=45",
    batch: null,
    id: "pkg45",
  },
  {
    name: "Koh Samui Retreat",
    duration: 8,
    country: "Thailand",
    highlights: ["Beach Time", "Spa Treatment", "Temple Tour"],
    price: 2499,
    rating: 5,
    image: "https://picsum.photos/400/250?random=46",
    batch: null,
    id: "pkg46",
  },
  {
    name: "Krabi Adventure",
    duration: 5,
    country: "Thailand",
    highlights: ["Rock Climbing", "Island Tours", "Hot Springs"],
    price: 1799,
    rating: 4,
    image: "https://picsum.photos/400/250?random=47",
    batch: null,
    id: "pkg47",
  },
  {
    name: "Ayutthaya History",
    duration: 4,
    country: "Thailand",
    highlights: ["Temple Ruins", "River Cruise", "Ancient Capital"],
    price: 1599,
    rating: 4,
    image: "https://picsum.photos/400/250?random=48",
    batch: null,
    id: "pkg48",
  },
  {
    name: "Dubai Luxury",
    duration: 5,
    country: "UAE",
    highlights: ["Desert Safari", "Burj Khalifa", "Gold Souk"],
    price: 2499,
    rating: 5,
    image: "https://picsum.photos/400/250?random=49",
    batch: null,
    id: "pkg49",
  },
  {
    name: "Abu Dhabi Culture",
    duration: 4,
    country: "UAE",
    highlights: ["Grand Mosque", "Ferrari World", "Heritage Village"],
    price: 1999,
    rating: 4,
    image: "https://picsum.photos/400/250?random=50",
    batch: null,
    id: "pkg50",
  },
  {
    name: "Ras Al Khaimah Adventure",
    duration: 5,
    country: "UAE",
    highlights: ["Mountain Zipline", "Desert Camp", "Beach Resort"],
    price: 1899,
    rating: 4,
    image: "https://picsum.photos/400/250?random=51",
    batch: null,
    id: "pkg51",
  },
  {
    name: "Fujairah Getaway",
    duration: 4,
    country: "UAE",
    highlights: ["Snorkeling Trip", "Historic Fort", "Mountain Views"],
    price: 1699,
    rating: 4,
    image: "https://picsum.photos/400/250?random=52",
    batch: null,
    id: "pkg52",
  },
  {
    name: "Sharjah Cultural Tour",
    duration: 3,
    country: "UAE",
    highlights: ["Art Museums", "Heritage Area", "Traditional Markets"],
    price: 1499,
    rating: 4,
    image: "https://picsum.photos/400/250?random=53",
    batch: null,
    id: "pkg53",
  },
  {
    name: "Ajman Beach Break",
    duration: 4,
    country: "UAE",
    highlights: ["Beach Activities", "Museum Visit", "Dhow Cruise"],
    price: 1599,
    rating: 4,
    image: "https://picsum.photos/400/250?random=54",
    batch: null,
    id: "pkg54",
  },
  {
    name: "Rio Carnival Experience",
    duration: 7,
    country: "Brazil",
    highlights: ["Carnival Parade", "Samba School", "Beach Time"],
    price: 2899,
    rating: 5,
    image: "https://picsum.photos/400/250?random=55",
    batch: null,
    id: "pkg55",
  },
  {
    name: "Amazon Adventure",
    duration: 6,
    country: "Brazil",
    highlights: ["Jungle Trek", "River Cruise", "Wildlife Spotting"],
    price: 2499,
    rating: 4,
    image: "https://picsum.photos/400/250?random=56",
    batch: null,
    id: "pkg56",
  },
  {
    name: "Mount Brazil Trek",
    duration: 8,
    country: "Brazil",
    highlights: ["Mountain Climbing", "Wildlife Spotting", "Forest Walks"],
    price: 2799,
    rating: 5,
    image: "https://picsum.photos/400/250?random=57",
    batch: null,
    id: "pkg57",
  },
  {
    name: "Salvador Culture",
    duration: 5,
    country: "Brazil",
    highlights: ["Historic Center", "African Culture", "Beach Life"],
    price: 1999,
    rating: 4,
    image: "https://picsum.photos/400/250?random=58",
    batch: null,
    id: "pkg58",
  },
  {
    name: "Iguazu Falls Wonder",
    duration: 4,
    country: "Brazil",
    highlights: ["Waterfall Tours", "Helicopter Ride", "Nature Walks"],
    price: 1899,
    rating: 5,
    image: "https://picsum.photos/400/250?random=59",
    batch: null,
    id: "pkg59",
  },
  {
    name: "Florianopolis Beach",
    duration: 6,
    country: "Brazil",
    highlights: ["Surf Lessons", "Island Tours", "Seafood Dining"],
    price: 2199,
    rating: 4,
    image: "https://picsum.photos/400/250?random=60",
    batch: null,
    id: "pkg60",
  },
];

export default TravelPackages;
